# SLF4J Configuration
org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.org.deeplearning4j=warn
org.slf4j.simpleLogger.log.org.nd4j=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
